// ${{ user }} - ${{ now.ctime() }}
// ${{ problem.name }} (${{ problem.url }})
// Generated by cptk

#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
using namespace std;

int main() {
    cin.tie(NULL)->sync_with_stdio(false);
}
