// ${{user}} - ${{ctime}}
// ${{problem.name}} (${{problem.url}})
// Generated by cptk

#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
using namespace std;

int main() {
    { std::cin.tie(0)->sync_with_stdio(false); }
}
