// User - Sat Jan  1 00:00:00 2022
// Test Problem (https://codeforces.com/problemset/problem/1/A)
// Generated by cptk

#include <algorithm>
#include <iostream>
#include <string>
#include <vector>
using namespace std;

int main() {
    cin.tie(NULL)->sync_with_stdio(false);
}