// ${{user}} - ${{ctime}}
// ${{problem.name}} (${{problem.url}})
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

int main() {
    { std::cin.tie(0)->sync_with_stdio(false); }
    
}
