// ${{ user }} - ${{ now.ctime() }}
// ${{ problem.name }} (${{ problem.url }})
// Generated by cptk

#include <bits/stdc++.h>
using namespace std;

int main() {
    cin.tie(NULL)->sync_with_stdio(false);
}
